version: "3.8"

services:
  graph360-client:
    container_name: "graph360"
    ports:
      - 3000:5173
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
