export enum FOLDER__NAME {
  USER__AVATAR = "USER__AVATAR",
  CLIENT_ATTACHMENTS = "CLIENT_ATTACHMENTS",
  SUPPLIER_ATTACHMENTS = "SUPPLIER_ATTACHMENTS",
  EMPLOYEE_ATTACHMENTS = "EMPLOYEE_ATTACHMENTS",
}
