export enum FOLDER__NAME {
  USER__AVATAR = "USER__AVATAR",
  CLIENT_ATTACHMENTS = "CLIENT_ATTACHMENTS",
  SUPPLIER_ATTACHMENTS = "SUPPLIER_ATTACHMENTS",
  EMPLOYEE_ATTACHMENTS = "EMPLOYEE_ATTACHMENTS",
  EXPENSE_ATTACHMENTS = "EXPENSE_ATTACHMENTS",
  PURCHASE_PAYMENTS_ATTACHMENTS = "PURCHASE_PAYMENTS_ATTACHMENTS",
}
